const UPDATE_WEB3_STATUS = "web3/status/update";

export default {
  UPDATE_WEB3_STATUS,
  GET_WALLET_ADDRESS: "GET_WALLET_ADDRESS",
  GET_WALLET_BALANCE: "GET_WALLET_BALANCE",
  GET_ADMIN: "GET_ADMIN"
  // CONNECTED: "CONNECTED_TO_WEB3"
};
