export const AT_ORDERS = {
  GET_ORDER: "GET_ORDER",
  GET_REFUNDING_ORDERS: "GET_REFUNDING_ORDERS",
  GET_ESCROW: "GET_ESCROW",
  GET_BUYER_ORDERS: "GET_BUYER_ORDER",
  GET_SELLER_ORDERS: "GET_SELLER_ORDERS",
  GET: "READ_ORDER",
  UPDATE: "CREATE_ORDER",
  DELETE: "DELETE_ORDER"
};
